// <auto-generated />
using System;
using DbConect;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BsuApi.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20231213211343_RemoveCode")]
    partial class RemoveCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Model.CourseGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Course")
                        .HasColumnType("longtext");

                    b.Property<string>("Group")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CourseGroup");
                });

            modelBuilder.Entity("Model.DayTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Day")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DayTime");
                });

            modelBuilder.Entity("Model.LessonForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Form")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LessonForm");
                });

            modelBuilder.Entity("Model.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("UserRole")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Model.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CGId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Classroom")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("DayId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IdForm")
                        .HasColumnType("char(36)");

                    b.Property<string>("Lecture")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Time")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CGId");

                    b.HasIndex("DayId");

                    b.HasIndex("IdForm");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("Model.UID", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Uid")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Uid");
                });

            modelBuilder.Entity("Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("IdCourseGroup")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IdRole")
                        .HasColumnType("char(36)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("SecondName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdCourseGroup");

                    b.HasIndex("IdRole");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Model.Schedule", b =>
                {
                    b.HasOne("Model.CourseGroup", "CorseGroup")
                        .WithMany("schedules")
                        .HasForeignKey("CGId");

                    b.HasOne("Model.DayTime", "DayTime")
                        .WithMany("Schedules")
                        .HasForeignKey("DayId");

                    b.HasOne("Model.LessonForm", "LessonForm")
                        .WithMany("Schedules")
                        .HasForeignKey("IdForm");

                    b.Navigation("CorseGroup");

                    b.Navigation("DayTime");

                    b.Navigation("LessonForm");
                });

            modelBuilder.Entity("Model.UID", b =>
                {
                    b.HasOne("Model.User", "User")
                        .WithMany("uIDs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Model.User", b =>
                {
                    b.HasOne("Model.CourseGroup", "CorseGroup")
                        .WithMany("users")
                        .HasForeignKey("IdCourseGroup");

                    b.HasOne("Model.Role", "userRole")
                        .WithMany("users")
                        .HasForeignKey("IdRole");

                    b.Navigation("CorseGroup");

                    b.Navigation("userRole");
                });

            modelBuilder.Entity("Model.CourseGroup", b =>
                {
                    b.Navigation("schedules");

                    b.Navigation("users");
                });

            modelBuilder.Entity("Model.DayTime", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Model.LessonForm", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Model.Role", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("Model.User", b =>
                {
                    b.Navigation("uIDs");
                });
#pragma warning restore 612, 618
        }
    }
}
